FROM golang:1.22.4 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/worker ./cmd/worker

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/bin/worker .
COPY --from=builder /app/config.yml .

CMD ["./worker"]
